### ISSUE TITLE
Post your feature (package) request here!

### ISSUE THREAD

**Issue by s-a** [sulu-one/sulu#11]
# GIT status like atom or code editor.  
![image](https://cloud.githubusercontent.com/assets/1270662/16091947/3776f1d2-3336-11e6-8ec6-dda3d7ecc05d.png)

**Comment by s-a** [comment]
# Add zip support

```javascript
var zlib = require('zlib');
var gzip = zlib.createGzip();
var fs = require('fs');
var inp = fs.createReadStream('input.txt');
var out = fs.createWriteStream('input.txt.gz');

inp.pipe(gzip).pipe(out);

**Comment by s-a** [comment]
# permanent delete

**Comment by s-a** [comment]
# sort file systemview

**Comment by s-a** [comment]
# remember last 50 history elements for every filesystemview

**Comment by s-a** [comment]
# command palette (plugin) (ctrl+shift+p)

**Comment by s-a** [comment]
# custom-key-bindings.json

**Comment by s-a** [comment]
# copy/cut and paste filesystem items within sulu gui

**Comment by s-a** [comment]
# copy & paste out of- and into SULU application

**Comment by s-a** [comment]
# Shadow/ghost path when navigate backwards to parent folder

**Comment by s-a** [comment]
# Compare file(s) and folder(s) package

**Comment by notslang** [comment]
> Compare file(s) and folder(s) package

Comparing files/folders seems way out-of-scope for a file manager, since it would require that sulu display the contents of files... It would make more sense to use an external diffing tool (like [meld](http://meldmerge.org/)) for that. However, I would love to see duplicate files / directories be marked by checking against an external data-source like btrfs/zfs reflinks (like [rmlint](https://rmlint.readthedocs.io/en/latest/) does) or some externally maintained list of file hashes. Just hashing the files for use in sulu would be extremely expensive, but displaying existing data would be great.

**Comment by s-a** [comment]
> Compare file(s) and folder(s) package

A custom external tool to compare is a great idea. As base functionality I mention  https://github.com/cemerick/jsdifflib which looks promising.

Regarding rmlint: In general it is easy to build adapters to any application via a new package. Maybe this will be a good prototype

**Comment by a-rose** [comment]
# Toggle hidden files and hidden folders display with ctrl+h.

**Comment by s-a** [comment]
I like this idea we could also mark hidden file system elements with a different icon and / or color.
